spring:
  datasource:
    url: jdbc:mysql://twn-mysql.mysql.database.azure.com:3306/employee
    username: admin1
    password: Password@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191


